### Particle Image Function
### Version: 1.0.4
### Width: 15
### Height: 15
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust 0.788 0.722 0.137 .5 ^1 ^0 ^ 0 0 0 0 1 force @a
particle minecraft:dust 0.788 0.722 0.137 .5 ^-1 ^0 ^ 0 0 0 0 1 force @a
particle portal ^ ^ ^ 0 0 0 1 10 force

particle minecraft:dust 0.5 0 0.5 .5 ^0.8666667 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.8666667 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.8666667 ^0 ^-0.0666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.8666667 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.8666667 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.8666667 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.7333333 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.7333333 ^0 ^-0.4666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.7333333 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.7333333 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.7333333 ^0 ^0.4666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.7333333 ^0 ^0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.6 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.6 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.6 ^0 ^0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.6 ^0 ^0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.4666667 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.4666667 ^0 ^0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.3333333 ^0 ^-0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.3333333 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.3333333 ^0 ^0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.3333333 ^0 ^0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.2 ^0 ^-0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.2 ^0 ^0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.0666667 ^0 ^-0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^0.0666667 ^0 ^0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.0666667 ^0 ^-0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.0666667 ^0 ^0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.2 ^0 ^-0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.2 ^0 ^0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.3333333 ^0 ^-0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.3333333 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.3333333 ^0 ^0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.3333333 ^0 ^0.8666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.4666667 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.4666667 ^0 ^0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.6 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.6 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.6 ^0 ^0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.6 ^0 ^0.7333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.7333333 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.7333333 ^0 ^-0.4666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.7333333 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.7333333 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.7333333 ^0 ^0.4666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.7333333 ^0 ^0.6 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.8666667 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.8666667 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.8666667 ^0 ^-0.0666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.8666667 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.8666667 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:dust 0.5 0 0.5 .5 ^-0.8666667 ^0 ^0.3333333 0 0 0 0 1 force @a
